# Generated by Django 3.2.3 on 2023-09-07 21:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0002_alter_item_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ordered_by',
            field=models.ManyToManyField(default='', to=settings.AUTH_USER_MODEL),
        ),
    ]
