# Generated by Django 3.2.3 on 2023-09-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_options'),
        ('Car', '0002_auto_20230907_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Avilable_battries',
            field=models.ManyToManyField(to='item.Item'),
        ),
    ]
