# Generated by Django 3.2.3 on 2023-09-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_ordered_by'),
        ('Car', '0003_car_avilable_battries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Avilable_battries',
            field=models.ManyToManyField(blank=True, null=True, to='item.Item'),
        ),
    ]
